-- ============================================================
-- SUIMS — Script 1: SEQUENCES
-- Smart University Internship Management System
-- Oracle Database 19c+
-- ============================================================

CREATE SEQUENCE seq_users START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_student_profiles START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_lecturer_profiles START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_company_profiles START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_password_resets START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;

CREATE SEQUENCE seq_cvs START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_cv_educations START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_cv_experiences START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_cv_documents START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_cv_versions START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;

CREATE SEQUENCE seq_skill_categories START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 10;
CREATE SEQUENCE seq_skills START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 10;
CREATE SEQUENCE seq_cv_skills START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 50;

CREATE SEQUENCE seq_internship_listings START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_listing_req_skills START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_recommendation_scores START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE SEQUENCE seq_applications START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_app_status_history START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 50;

CREATE SEQUENCE seq_internships START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;

CREATE SEQUENCE seq_weekly_reports START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 50;
CREATE SEQUENCE seq_report_attachments START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_report_reviews START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 50;

CREATE SEQUENCE seq_company_evaluations START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_eval_criteria_scores START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 50;
CREATE SEQUENCE seq_lecturer_grades START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE seq_final_scores START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;

CREATE SEQUENCE seq_notifications START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE SEQUENCE seq_system_configs START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 5;
CREATE SEQUENCE seq_grading_scales START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 5;
CREATE SEQUENCE seq_evaluation_criteria START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 5;

CREATE SEQUENCE seq_audit_logs START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
